services:
  server:
    build:
      context: ./server
      dockerfile: ../docker/server/Dockerfile
    env_file: .env
    ports:
      - "${SERVER_PORT}:3000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile
    env_file: .env
    ports:
      - "${CLIENT_PORT}:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
